require: rubocop-rails
Documentation:
  Enabled: false
Layout/LineLength:
  Max: 99
  IgnoredPatterns: ['\A#', '\s#']
Metrics/BlockLength:
  IgnoredMethods: ['describe', 'context']
Style/FrozenStringLiteralComment:
  Enabled: false
Style/ClassAndModuleChildren:
  EnforcedStyle: compact
AllCops:
  Exclude:
    - bin/*
    - db/**
    - node_modules/**/*
    - script/**
    - vendor/**/*
